//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contract
    {
        public int ContractId { get; set; }

        [Display(Name ="Your Email")]
        public string DelegateEmail { get; set; }

        [Display(Name = "Start date of the contract")]
        public Nullable<System.DateTime> ContractStartDate { get; set; }

        [Display(Name = "End Date of the contract")]
        public Nullable<System.DateTime> ContractEndDate { get; set; }

        [Display(Name = "Company's Name")]
        public string CompanyName { get; set; }

        [Display(Name = "Address")]
        public string CompanyAddress { get; set; }

        [Display(Name = "City")]
        public string CompanyCity { get; set; }

        [Display(Name = "State")]
        public string CompanyState { get; set; }

        [Display(Name = "Zip")]
        public string CompanyZip { get; set; }

        [Display(Name = "Email")]
        public string CompanyEmail { get; set; }

        [Display(Name = "Fax")]
        public string CompanyFax { get; set; }

        [Display(Name = "Preferred Method of Contact")]
        public string CompanyMethodOfContact { get; set; }

        [Display(Name = "First Name")]
        public string ProviderFirstName { get; set; }

        [Display(Name = "Last Name")]
        public string ProviderLastName { get; set; }

        [Display(Name = "Number")]
        public string ProviderNumber { get; set; }

        [Display(Name = "Provider's Amount")]
        public string ProviderAmount { get; set; }

        [Display(Name = "Services being Provided")]
        public string ProviderTypeOfService { get; set; }

        [Display(Name = "Payment terms-info related to invoicing")]
        public string ProviderPaymentTerms { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }
    }
}
